# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  
test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5

cucumber:
  <<: *TEST
